### ISSUE TITLE
May I ask if you can publish the code for RGB-D SOD

### ISSUE THREAD

**Issue by YangTuo66** [VCIP-RGBD/DFormer#10]
Hello, your paper mentions the relevant work of RGB-D salient object detection. Can you provide the corresponding code?

**Comment by yinbow** [comment]
Sure! Thanks for your attention. We have provided the code at https://github.com/VCIP-RGBD/DFormer-SOD. You can refer to this.

**Comment by YangTuo66** [comment]
So fast! Thank you.
