### ISSUE TITLE
How to check FLOPs

### ISSUE THREAD

**Issue by catchyoo** [VCIP-RGBD/DFormer#11]
Hello! Thank you for your hard work.

The paper includes calculations of FLOPs in a table, but upon reviewing the code, it's challenging to locate where FLOPs are measured. 

Could you possibly tell me where it is measured?"

**Comment by yinbow** [comment]
Thanks for your attention!

We upload the code for calculations of FLOPs.
You can use `PYTHONPATH="$(dirname $0)/..":$PYTHONPATH python benchmark.py --config local_configs.NYUDepthv2.DFormer_Large' to calculate the Flops and Params.

**Comment by catchyoo** [comment]
Thank you!!
