### ISSUE TITLE
您好，请问该项目有支持windows系统的代码吗？

### ISSUE THREAD

**Issue by 1404561326521** [VCIP-RGBD/DFormer#16]
作者您好，我在自己数据集上复现了该模型，在使用infer.py时我想debug每个步骤的具体结果，但是该脚本似乎不支持在windows系统下运行，请问作者是否有相应代码，十分感谢！！！

**Comment by caojiaolong** [comment]
感谢您的反馈和对我们项目的关注！

对于您在 Windows 系统下使用 infer.py 遇到的问题，我们很抱歉。通常情况下，我们的代码应该是跨平台兼容的，但可能会存在一些疏漏或者bug，导致无法运行。您可以尝试以下几种解决方案：

1. 确保您的 Python 环境以及所需的库，例如torch、mmcv等，都已正确安装，并且与我们项目所需的版本相匹配。此外，CUDA版本或者nvidia驱动版本不匹配也有可能导致无法运行。
2. 尝试在 Windows PowerShell 或者 Git Bash 等其他终端中运行脚本，看是否能够解决问题。
3. 如果您能提供具体的报错描述，我们将能更好地定位问题。

若仍不能解决，您可以再给出一些具体的报错信息。

**Comment by 1404561326521** [comment]
在本地打开该项目时会提示缺少相应参数，例如：
![image](https://github.com/VCIP-RGBD/DFormer/assets/72433565/945fc66c-1806-4a16-8eef-e76f5fc9b95b)

**Comment by caojiaolong** [comment]
根据您的截图，我们认为问题可能出在以下两个之一：

1. Python调试出现OSError: [WinError 193] %1 不是有效的 Win32 应用程序，一般来讲是因为python位数和dll位数不一样导致的，dll是32位的，而python是64位的。
2. 检查自己的anaconda是否配好了环境变量

建议参考[这篇博客](https://blog.csdn.net/weixin_51080803/article/details/135222182) 。

您截图中框出的config变量没有定义的问题，是由于您截图中的第51行使用了exec命令引入的config，可以正常运行，但是无法被IDE识别到，这不是一个错误，不需要修改config相关的警告。

**Comment by 1404561326521** [comment]
好的感谢提醒！
