### ISSUE TITLE
Single GPU training

### ISSUE THREAD

**Issue by lili0620** [VCIP-RGBD/DFormer#2]
Thanks for your excellent work! I melt the issue when training the model with a single 3090 GPU. I cannot sort out the source of the issue.

>RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by yinbow** [comment]
I was using 'syncBN' in the model, but I hadn't switched it to standard BN when working with a single GPU. I've fixed that now. Thanks for the reminder.
