### ISSUE TITLE
How to pretrain in imagenet1k?

### ISSUE THREAD

**Issue by ZivHong** [VCIP-RGBD/DFormer#23]
Your work are awesome, the gratest part is pretrained in imagenet-1k that could provide a good basis for transfer learning in other task. However, I couldn't reproduce the training procedure only by Table 17 ,I'm wondering if you could provide the code for pretraining in imagenet-1k. Thank you for your response beforehand.

**Comment by yinbow** [comment]
Sure. Thanks for your attention to our work. For the pretrain code, you can refer to https://github.com/VCIP-RGBD/RGBD-Pretrain .

**Comment by ZivHong** [comment]
I don't notice you had provide the information in readme, I apologize for my mistake. I appreciate your message, thank you a lot.

**Comment by yinbow** [comment]
Never mind 😃 . If you have any other questions about our work, feel free to contact me.
