### ISSUE TITLE
Train&Test_image_size

### ISSUE THREAD

**Issue by Mendopower** [VCIP-RGBD/DFormer#26]
Hello there! Thank you for your wonderful work here, I would like to know if it is possible to test the model using images in different size from the training images. More specifically, can I use larger images that maintain the same aspect ratio for testing? I would appreciate it if you reply.

**Comment by yinbow** [comment]
Thanks for your attention to our work!

It is OK to test the model using images in a different size from the training images. Usually, in multi-scale testing,  the model uses the test image that is enlarged with ratio {0.5,0.75,1.0,1.25,1.5} for more robust results. You can directly use the images with different sizes. 

However, the performance may drop if the sizes vary in a large range, such as 512*512 to 1024*1024. It is suggested that train the model with similar sizes. Or, you can use sliding window testing, which splits a large image into several parts and runs the model on each part.

**Comment by Mendopower** [comment]
Thank you for your kind reply, it helps a lot. One more question:  Can I train this model on a single GPU by simply modifying the command?

**Comment by yinbow** [comment]
Yes. Our framework supports training on a single GPU.

**Comment by Mendopower** [comment]
Thx！
