### ISSUE TITLE
Continue to train on the trained model

### ISSUE THREAD

**Issue by ascacdsaa** [VCIP-RGBD/DFormer#29]
Dear author, can your code continue to train on the basis of the trained model? What should be changed? Thank you.

**Comment by yinbow** [comment]
You can load the weight of the trained model by adding the following code after the definition of the model at train.py (line 192):
```
weight=torch.load(your_model_path)['model']
model.load_state_dict(weight)
```

**Comment by ascacdsaa** [comment]
Thank you very much for your reply. It has been very helpful to me.
