### ISSUE TITLE
权重文件加载

### ISSUE THREAD

**Issue by finetune-master** [VCIP-RGBD/DFormer#6]
##### 期待您的回复

**Comment by yinbow** [comment]
您好，首先感谢您对我们工作的关注！

加载.pth和.pth.tar文件的方法在大多数情况下是相似的，因为它们都是使用PyTorch提供的torch.load()函数来加载模型的权重。两者的一般加载形式如下：

对于pth:
 model.load_state_dict(torch.load('model_weights.pth'))

对于pth.tar: 
checkpoint = torch.load('model_checkpoint.pth.tar')
model.load_state_dict(checkpoint['state_dict'])

pth文件是PyTorch中常见的权重文件扩展名，仅包含了模型的权重参数，但不包含任何其他信息，例如模型的架构或优化器状态。.pth.tar文件是一个经过打包（tar压缩）的权重文件，通常包含了除了权重之外的其他信息。
它可以包含模型的架构信息、训练时的优化器状态以及其他相关信息。

**Comment by finetune-master** [comment]
> 您好，首先感谢您对我们工作的关注！
> 
> 加载.pth和.pth.tar文件的方法在大多数情况下是相似的，因为它们都是使用PyTorch提供的torch.load()函数来加载模型的权重。两者的一般加载形式如下：
> 
> 对于pth: model.load_state_dict(torch.load('model_weights.pth'))
> 
> 对于pth.tar: checkpoint = torch.load('model_checkpoint.pth.tar') model.load_state_dict(checkpoint['state_dict'])
> 
> pth文件是PyTorch中常见的权重文件扩展名，仅包含了模型的权重参数，但不包含任何其他信息，例如模型的架构或优化器状态。.pth.tar文件是一个经过打包（tar压缩）的权重文件，通常包含了除了权重之外的其他信息。 它可以包含模型的架构信息、训练时的优化器状态以及其他相关信息。
> 
> 希望我的回答可以解决您的问题。

##### 非常感谢您的回答
