### ISSUE TITLE
怎么跑自制数据集？

### ISSUE THREAD

**Issue by wuYwen1** [VCIP-RGBD/DFormer#7]
感谢您杰出的工作，我尝试用自己制作的数据集去运行您的代码，出现了一些错误，loss=nan，以下是一些错误信息
27 23:43:55 Initing weights ...
27 23:44:00 begin trainning:
Epoch 1/500 Iter 156/156: lr=5.9615e-06 loss=nan total_loss=nan: [01:48<00:00, 1.44it/s]
27 23:45:48 WRN NaN or Inf found in input tensor.
期待您的答复

**Comment by yinbow** [comment]
您好，非常感谢您对于我们工作的关注！

迁移到新的数据机上出现nan的情况可能有很多，比如：

（1）数据问题： 数据预处理不当或数据集中包含异常数值也可能导致数值不稳定性。

（2）学习率过大： 如果学习率设置得太大，可能导致参数更新过大，使权重变得很大或者很小，从而使激活函数的输出变得非常大或非常小，最终导致NaN的情况。

可能对于新的数据集要做调整。
您给出的描述较少，没法准确判断问题，也可以联系我一起讨论下，有需要的话可以发邮件给我 bowenyin@mail.nankai.edu.cn ，我回复您我的微信聊聊。

**Comment by cht619** [comment]
depth可以自己生成吗？

**Comment by caojiaolong** [comment]
> depth可以自己生成吗？

您好，如果没有真实的depth数据也可以使用自己生成的depth。

例如[Depth Anything](https://github.com/LiheYoung/Depth-Anything)等单目深度估计方法可以从RGB图像中生成较为真实的depth数据。
