### ISSUE TITLE
自制数据集的要求

### ISSUE THREAD

**Issue by yuan-shi-sys** [VCIP-RGBD/DFormer#8]
感谢您杰出的工作。我想要自己制作数据集去运行您的代码，想知道代码对数据集有什么样的要求？

**Comment by yinbow** [comment]
您好，感谢您的关注！

DFormer是一个通用的RGBD编码器，用于实现有效的RGBD信息编码，目前这个代码框架主要用于分割，如果您是做其他任务也可以考虑把DFormer （encoder）迁移到其他代码框架，如果也是做分割任务，可以修改local_config中的config来换成新的数据集。

之前也有一位朋友将本框架迁移到他的自制数据集上，过程中我们发现，对数据的要求主要有如下几点：

数据集具有RGB-D数据和label，RGB就是普通的图片格式即可，depth图则是灰度图，越远越亮，越近越暗，0（最近）-255（最远）， label是灰度图中假设有N类，则标签应该分别是 0，1，2，.......,N,其中0是背景类，不会计算loss。
同时还需要生成一下train.txt和test.txt，用于索引训练测试数据。

基本上满足以上几个条件就可以直接使用DFormer进行适配了。同时学习率等超参可能也需要相应调整。
考虑到最近有不少朋友和我讨论如何迁移到其他数据集，我会在近期更新一个迁移教程到本repo（12月4日之前），用于描述怎么将新的数据集适配到本框架下，到时我也会在本问题下提醒您。

**Comment by yinbow** [comment]
我们更新了添加新数据集的说明，您可以参考这个[Application to new datasets](https://github.com/VCIP-RGBD/DFormer/tree/main/figs/application_new_dataset). 如果有任何问题或建议，可以随时提issue或是发邮件联系我 （bowenyin@mail.nankai.edu.cn）。
