### ISSUE TITLE
可以提供一下伪深度图吗？

### ISSUE THREAD

**Issue by zhangjinCV** [VCIP-RGBD/DFormer#9]
可以提供一下伪深度图吗？

**Comment by yinbow** [comment]
您好，我上传网盘了，您可以从这里下载： 

链接：https://pan.baidu.com/s/1rgsTiFXUTjrSscWCi325-A?pwd=u2kb 
提取码：u2kb

**Comment by zhangjinCV** [comment]
非常感谢，祝ICLR中稿

**Comment by yinbow** [comment]
多谢您啦，也祝您科研顺利！
